let inputWidth;
let inputHeight;
inputWidth = prompt("Enter the width");
inputHeight = prompt("Enter the height");
let width = parseInt(inputWidth);
let height = parseInt(inputHeight);
let area = width * height;
document.write("Height : " + height);
document.write("<br/>");
document.write("Width : " + width);
document.write("<br/>");
document.write("The area is: " + area);